server:
  port: 8082

spring:
  application:
    name: order-service #服务名
#连接注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7070/eureka/
  instance:
    prefer-ip-address: true  #支持域名直接解析ip

#断路器配置
circuitBreaker:
  # 请求总数下限
  requestVolumeThreshold: 20
  # 休眠时间窗
  sleepWindowInMilliseconds: 3000
  # 错误百分比下限
  errorThresholdPercentage: 50
feign:
  hystrix:
    enabled: true